## Imports

In [81]:
import pandas as pd
import altair as alt
import tabula

## Data read-in

In [82]:
# Read in data and filter to desired DF
dfs = tabula.read_pdf('2023-news-release-july-1st-preliminary-taxable-values.pdf',pages=2)
df = dfs[0]

In [83]:
# Rename columns
df = df.rename(columns={'Unnamed: 0':'TAXING AUTHORITY',
                                '2022':'2022 PRELIMINARY TAXABLE VALUE',
                                '2023':'2023 TAXABLE VALUE BEFORE NEW CONSTRUCTION',
                               'Unnamed: 1':'PERCENT CHANGE',
                               'Unnamed: 2':'NEW CONSTRUCTION',
                               '2023.1':'2023 PRELIMINARY TAXABLE VALUE',
                               'Unnamed: 3':'PERCENT CHANGE FROM 2022',
                               'Unnamed: 4':'NET VALUE CHANGE'})

In [84]:
# Remove bad rows
df = df.drop(index=[0,1,2,40])

In [85]:
# Reset index
df = df.reset_index()

In [86]:
# Drop old index
df = df.drop(columns='index')

In [87]:
df

,TAXING AUTHORITY,2022 PRELIMINARY TAXABLE VALUE,2023 TAXABLE VALUE BEFORE NEW CONSTRUCTION,PERCENT CHANGE,NEW CONSTRUCTION,2023 PRELIMINARY TAXABLE VALUE,PERCENT CHANGE FROM 2022,NET VALUE CHANGE
0,01 MIAMI,"73,749,481,211","83,042,917,479",12.6%,"1,408,850,944","84,451,768,423",14.5%,"10,702,287,212"
1,0101 MIAMI ( DDA ),"24,602,533,803","27,528,563,602",11.9%,"171,237,637","27,699,801,239",12.6%,"3,097,267,436"
2,02 MIAMI BEACH,"46,544,694,070","51,346,874,323",10.3%,"213,897,907","51,560,772,230",10.8%,"5,016,078,160"
3,0201 MB NORMANDY SHORES,"305,472,912","389,416,157",27.5%,"3,369,531","392,785,688",28.6%,"87,312,776"
4,03 CORAL GABLES,"20,101,009,587","22,188,650,684",10.4%,"454,317,791","22,642,968,475",12.6%,"2,541,958,888"
5,04 HIALEAH,"15,369,871,099","17,249,692,407",12.2%,"300,274,188","17,549,966,595",14.2%,"2,180,095,496"
6,05 MIAMI SPRINGS,"1,449,806,131","1,598,589,815",10.3%,"6,968,534","1,605,558,349",10.7%,"155,752,218"
7,06 NORTH MIAMI,"4,605,444,600","5,199,015,711",12.9%,"61,074,883","5,260,090,594",14.2%,"654,645,994"
8,07 NORTH MIAMI BEACH,"4,113,425,952","4,751,311,110",15.5%,"-767,739","4,750,543,371",15.5%,"637,117,419"
9,08 OPA-LOCKA,"1,551,388,190","1,681,633,415",8.4%,"36,607,979","1,718,241,394",10.8%,"166,853,204"
10,09 SOUTH MIAMI,"2,362,980,956","2,594,599,843",9.8%,"21,675,030","2,616,274,873",10.7%,"253,293,917"
11,10 HOMESTEAD,"4,360,611,776","4,857,657,631",11.4%,"205,477,290","5,063,134,921",16.1%,"702,523,145"
12,11 MIAMI SHORES,"1,535,464,298","1,750,478,152",14.0%,"5,829,579","1,756,307,731",14.4%,"220,843,433"
13,12 BAL HARBOUR,"5,774,201,876","6,274,293,306",8.7%,"6,540,050","6,280,833,356",8.8%,"506,631,480"
14,13 BAY HARBOR ISLANDS,"1,632,803,218","1,897,251,661",16.2%,"7,656,325","1,904,907,986",16.7%,"272,104,768"
15,14 SURFSIDE,"3,651,048,630","4,100,952,343",12.3%,"2,848,874","4,103,801,217",12.4%,"452,752,587"
16,15 WEST MIAMI,"828,793,856","894,009,798",7.9%,"1,149,691","895,159,489",8.0%,"66,365,633"
17,16 FLORIDA CITY,"925,481,705","1,008,270,748",8.9%,"109,520,981","1,117,791,729",20.8%,"192,310,024"
18,17 BISCAYNE PARK,"309,707,689","367,160,688",18.6%,"1,402,108","368,562,796",19.0%,"58,855,107"
19,18 EL PORTAL,"226,240,502","267,164,694",18.1%,"1,638,401","268,803,095",18.8%,"42,562,593"
20,19 GOLDEN BEACH,"1,438,422,337","1,631,641,324",13.4%,"25,137,052","1,656,778,376",15.2%,"218,356,039"
21,20 PINECREST,"6,066,710,208","6,693,432,650",10.3%,"128,225,734","6,821,658,384",12.4%,"754,948,176"
22,21 INDIAN CREEK,"831,971,445","888,017,751",6.7%,"-3,043,912","884,973,839",6.4%,"53,002,394"
23,22 MEDLEY,"3,205,242,164","3,748,826,042",17.0%,"1,443,774,310","5,192,600,352",62.0%,"1,987,358,188"
24,23 N. BAY VILLAGE,"1,311,100,447","1,466,105,773",11.8%,"3,185,548","1,469,291,321",12.1%,"158,190,874"
25,24 KEY BISCAYNE,"9,096,495,184","9,968,909,769",9.6%,"9,607,463","9,978,517,232",9.7%,"882,022,048"
26,25 SWEETWATER,"3,307,159,031","3,777,554,435",14.2%,"48,003,006","3,825,557,441",15.7%,"518,398,410"
27,26 VIRGINIA GARDENS,"372,489,301","366,459,811",-1.6%,"132,325","366,592,136",-1.6%,"-5,897,165"
28,27 HIALEAH GARDENS,"1,768,783,577","2,041,496,401",15.4%,"55,184,144","2,096,680,545",18.5%,"327,896,968"
29,28 AVENTURA,"11,368,391,539","12,483,595,481",9.8%,"22,439,761","12,506,035,242",10.0%,"1,137,643,703"
30,30 UNINCORPORATED,"101,823,792,808","111,878,021,546",9.9%,"804,330,957","112,682,352,503",10.7%,"10,858,559,695"
31,31 SUNNY ISLES BEACH,"13,781,795,040","15,312,131,485",11.1%,"656,276,116","15,968,407,601",15.9%,"2,186,612,561"
32,32 MIAMI LAKES,"4,131,041,213","4,496,156,094",8.8%,"19,189,005","4,515,345,099",9.3%,"384,303,886"
33,33 PALMETTO BAY,"3,714,374,050","4,115,885,611",10.8%,"56,131,705","4,172,017,316",12.3%,"457,643,266"
34,34 MIAMI GARDENS,"6,868,956,173","7,711,714,826",12.3%,"179,017,837","7,890,732,663",14.9%,"1,021,776,490"
35,35 DORAL,"16,609,380,949","18,060,824,021",8.7%,"292,580,988","18,353,405,009",10.5%,"1,744,024,060"
36,36 CUTLER BAY,"3,261,804,057","3,638,209,519",11.5%,"29,897,490","3,668,107,009",12.5%,"406,302,952"
37,COUNTY-WIDE,"377,897,396,044","419,806,032,546",11.1%,"6,010,848,470","425,816,881,016",12.7%,"47,919,484,972"
38,FIRE AND RESCUE,"213,164,959,610","236,094,391,135",10.8%,"3,663,580,273","239,757,971,408",12.5%,"26,593,011,798"
39,LIBRARY,"338,627,116,797","375,734,290,374",11.0%,"5,454,199,453","381,188,489,827",12.6%,"42,561,373,030"
40,SCHOOL BOARD,"428,837,004,339","503,418,361,517",17.4%,"6,014,600,589","509,432,962,106",18.8%,"80,595,957,767"
41,S FL WATER MNGT DIST,"379,933,131,965","421,794,790,410",11.0%,"6,014,600,049","427,809,390,459",12.6%,"47,876,258,494"
42,FL INLAND NAV DIST,"379,933,131,965","421,794,790,410",11.0%,"6,014,600,049","427,809,390,459",12.6%,"47,876,258,494"
43,THE CHILDREN'S TRUST,"379,933,131,965","421,794,790,410",11.0%,"6,014,600,049","427,809,390,459",12.6%,"47,876,258,494"